### ISSUE TITLE
Didnt work in hexo 4.2

### ISSUE THREAD

**Issue by MrBe1ieVe** [cnzsb/hexo-asset#3]
when my link is `http://localhost:4000/2020/03/06/%E5%95%86%E4%B8%9A%E8%AE%A1%E5%88%92%E4%B9%A6%E6%92%B0%E5%86%99%E5%8F%8A%E6%A1%88%E4%BE%8B%E5%88%86%E6%9E%90/`
the img src is `src="/.com//image-20200303154014932.png"` 
it didn show up.But i can get it when im using `http://localhost:4000/2020/03/06/%E5%95%86%E4%B8%9A%E8%AE%A1%E5%88%92%E4%B9%A6%E6%92%B0%E5%86%99%E5%8F%8A%E6%A1%88%E4%BE%8B%E5%88%86%E6%9E%90/image-20200303154014932.png`
it work before i upgrade the hexo.

I use file_name.assests/image to store my images when im writing , when I publish it will change folder's name to the same name as markdown file.

By the way this way looks like a solution:[link](https://blog.csdn.net/qq904305159/article/details/104162802)

**Comment by cnzsb** [comment]
Hi, @mrbelieve128.
It still works in hexo@4.2.0. For this plugin, image paths will not be modified for those started with `http`, `https`, `//`, `/` and plain string(like `path/asset.jpg`).
And I think you should put your images in the `_posts.images` directory, then you can directly use the image path with `./images/image-whatever.png` since your blog is right in the `_posts` directory. After magic with this plugin, the final path will be `/your_post_path/image-whatever.png`.
BTW, don't miss `post_asset_folder: true` in your `_config.yml`.
